name: 컨테이너 기반 배포하기

on:
  push:
    branches:
      - main

jobs:
  ContainerBased-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 의 파일 가져오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 디렉토리와 환경 변수 확인
        run: |
          echo "현재 디렉토리:"
          pwd
          cd src
          ls
          cd main
          echo "src/main/resources 디렉토리 존재 여부:"
          ls -al ./src/main/resources || echo "디렉토리가 존재하지 않습니다."

      - name: application.yml 파일 생성
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: AWS ECR 접근하기 위해 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_PUBLIC }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_PRIVATE }}

      - name: AWS ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t web-final .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag web-final ${{ steps.login-ecr.outputs.registry }}/web-final:latest

      - name: ECR에 Docker 이미지 push
        run: docker push ${{ steps.login-ecr.outputs.registry }}/web-final:latest
